initial HPC testing and analysis of original, NGS data (#16)
* santa fixes

Addressing #3 - errorStrategy 'ignore' to continue pipe when non-viable population is generated. Need to be wary of other potential errors.

Soft coded sequence file.

* 3seq outputs correct number of files

* rename channels, phipack outputs individual files correctly

* phipack and 3seq process simulated and empirical data for mutrates (2 reps)

* replaced output wildcard globs with specific outputs

* main.nf sweeps mutRate and recRate

* formatting

* moved mutRate and recRate values into channel for cfml tree input

* main.nf outputs empirical cfml

* add hyphy bin and initial cfml_s code

* Create sumstats.py

Script to summarise output files. Starting with phipack outs, needs lots more work.

* Update sumstats.py

Accounts for '--' outputs in PhiPack test, but only in the fourth test. Need to add '--' for first three tests.

* update empirical.nf

specific outputs added. Delete 'gaps' for uchime input

* adding phipack profile, R and py scripts for processing I/Os

* Rscripts to visualise outputs

Phi and 3seq for single replicate of empirical data. Phi updated to invert pvalue for eligibility

* uchime (sim and emp) added to main.nf. Tweaks.

* cfml_s fixes

Paired inputs now work, but only do one rep. Amended hcv_santa.xml sample equal number of inds for trees and sequences

* Update main.nf

* Revert "cfml_s fixes"

This reverts commit 397309ff3843711d29cc623378c42bb643854986.

* Revert "Update main.nf"

This reverts commit 679b698b2e8693e7e585144a99b9af1fab29c1c7.

* cfml_s fixes

* update .py script to do all fasta preprocessing

* update to run using kenya fmdv

cfml_s broken. phi_profile_e output names and scripts broken.

* add data and output files

* Update fasta_preprocess.py

Big improvement:
- Subs characters
- Reads any .fasta specified via command-line
- Outputs histograms of sequence lengths, before and after gaps are removed

* Update fasta_preprocess.py

script now outputs .fa file removing sequences with gaps. Add tests (refine later), formatting.

* starting run with empirical hcv dataset

clean dir, add input .fa, update santa-sim xml, fix fasta_preprocess.py. hcv_minimal.nf adds seqNum sweep

* tweaks to .nf and adding singularity.def

trying to run this on the hpc.  attempt to build container on shub?

* Update python.def

* Update python.def

* Update python.def

* Update python.def

* Update python.def

Error: from pip import main
ImportError: cannot import name main

Solution?: https://github.com/pypa/pip/issues/5221

* Update python.def

* Update python.def

Trying with another OS

* Update python.def

* Update python.def

* Update python.def

no gzip for extraction

* Update python.def

* Update python.def

is pip already installed with python 3.4+?

* Update python.def

* Update python.def

* nextflow config for enabling containers

* Update python.def

literally removing one space

* add phipack to container

* Update recbench.def

* Update hcv_minimal.nf

Better. Doesn't require two executions due to Channel.from()

* Updates for hpc

small tweaks to output name, splitting singularity into one base and mutiple imges

* rename for automated build?

* Create Singularity.prepro

* update simg

* Update Singularity.phi

* Update Singularity.phi

* Update Singularity.phi

* Update Singularity.phi

test

* Update Singularity.phi

* Update Singularity.phi

I think this works now

* hpc updates

Singularity.phi works in pipe, but fails test as command not found?

* update .gitignore and add nextflow.config

* update readme and file names

PR

* Update clean.sh

* Delete FMDV_Kenya_4refs_alg_m.fasta

* Delete FMDV_Kenya_4refs_alg_n2.fasta

* Delete FMDV_Kenya_4refs_alg_n.fasta

* Update README.md

* Update .gitignore

* Update .gitignore

oops